# Generated by Django 3.2.2 on 2021-05-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bei', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
